
S3_DST_BUCKET: "nextstrain-ncov-private/100k"
S3_DST_ORIGINS: [needed-for-workflow-but-unused]
deploy_url: needed_for_workflow_but_unused

custom_rules:
  - workflow/snakemake_rules/export_for_nextstrain.smk

# Note: unaligned sequences are provided as "aligned" sequences to avoid an initial full-DB alignment
inputs:
  - name: gisaid
    metadata: "s3://nextstrain-ncov-private/metadata.tsv.zst"
    aligned: "s3://nextstrain-ncov-private/sequences.fasta.zst"
    skip_sanitize_metadata: true

builds:
  100k:
    subsampling_scheme: 100k_scheme

# mapping of remote: local files to be uploaded under S3_DST_BUCKET
upload:
  metadata.tsv.xz: results/100k/100k_subsampled_metadata.tsv.xz
  sequences.fasta.xz: results/100k/100k_subsampled_sequences.fasta.xz

# remove sequences without division label in US
filter:
  exclude_where: "division='USA'"

# We wish to subsample 50k in the previous 12 months and 50k prior to that.
# Note 1: both --max-date and --min-date are inclusive of the boundary date,
#         so sequences from that date will be available to both sub-samples
# Note 2: As we group by (year,month) the boundary month will be included
#         in both sub-samples and thus this month will be oversampled.
#         For instance, if the boundary is March 7th then `50k_early` will sample
#         the same number of genomes from the first week of March as each of the
#         preceding months; similarly `50k_late` will sample as many genomes from
#         the final ~3 weeks of March as each of the following full months.
# (see https://github.com/nextstrain/ncov/pull/1032#discussion_r1034087312)
subsampling:
  100k_scheme:
    50k_early:
      group_by: "year month country"
      max_sequences: 50000
      max_date: "--max-date 1Y"
    50k_late:
      group_by: "year month country"
      max_sequences: 50000
      min_date: "--min-date 1Y"
