configfile:
  - defaults/parameters.yaml
  - nextstrain_profiles/nextstrain-gisaid-21L/builds.yaml

cores: 8
keep-going: False
printshellcmds: True
show-failed-logs: True
restart-times: 2
set-threads: tree=4
