name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test-build:
    uses: nextstrain/.github/.github/workflows/pathogen-repo-ci.yaml@v0
    with:
      build-args: all_regions -j 2 --configfile nextstrain_configs/gisaid/builds.yaml nextstrain_configs/ci/builds.yaml

  test-cram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - run: pip install cram nextstrain-augur
      - run: cram --shell=/bin/bash tests/sanitize-metadata.t
