name: Rebuild open (GenBank) phylogenetic datasets

on:
  # This workflow can be triggered from repository_dispatch events,
  # for instance, after the appropriate preprocessing actions have completed
  repository_dispatch:
    types:
      - rebuild
      - open/rebuild
      - genbank/rebuild
  # Manually triggered using GitHub's UI
  workflow_dispatch:
    inputs:
      trial_name:
        description: "Short name for this trial build, for prefixing the uploaded data and results files. WARNING: without this we will overwrite files in s3://nextstrain-data/files/ncov/open/ and the trees on nextstrain.org/ncov/open/..."
        required: false
      image:
        description: 'Specific container image to use for build (e.g. `nextstrain/base:branch-test`, `ghcr.io/user/repo:tag`)'
        required: false

jobs:
  open:
    permissions:
      id-token: write
    uses: nextstrain/.github/.github/workflows/pathogen-repo-build.yaml@master
    secrets: inherit
    with:
      runtime: aws-batch
      env: |
        TRIAL_NAME: ${{ github.event.inputs.trial_name }}
        NEXTSTRAIN_DOCKER_IMAGE: ${{ github.event.inputs.image }}
      run: |
        set -x

        declare -a config
        config+=(build_date=\'$(date +'%Y-%m-%d')\')
        if [[ "$TRIAL_NAME" ]]; then
          config+=(
            S3_DST_BUCKET=nextstrain-staging/files/ncov/open/trial/"$TRIAL_NAME"
            deploy_url=s3://nextstrain-staging/
            auspice_json_prefix=ncov_open_trial_"$TRIAL_NAME"
          )
        else
          config+=(slack_token=$SLACK_TOKEN)
        fi

        nextstrain build \
          --detach \
          --cpus 72 \
          --memory 140GiB \
          . \
            deploy \
            upload \
            --config "${config[@]}" \
            --profile nextstrain_profiles/nextstrain-open \
            --set-threads tree=8
